name: my_food_app
description: "A simple Flutter food tracker app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  shared_preferences: ^2.1.1 

  # Data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # COMPATIBLE versions with hive_generator 2.0.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/foods.json
    - assets/lottie/Food_prep.json

